# Generated by Django 2.2.2 on 2019-06-13 16:30

from django.db import migrations
from products.models import Category


def create_default_category(apps, schema_editor):
    Category.objects.create(
        name='Vegetables'
    )



class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category'),
    ]

    operations = [
        migrations.RunPython(create_default_category)
    ]
